name = "AIProofTD"
version = "0.1.0"
defaultTargets = ["Exercises", "Solutions"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0-rc1"

[[lean_lib]]
name = "Exercises"

[[lean_lib]]
name = "Solutions"
